# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: CI/CD Pipeline with Java x Maven and React x Node

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ikalnytskyi/action-setup-postgres@v6
        with:
          username: ${{ secrets.POSTGRES_USERNAME }}
          password: ${{ secrets.POSTGRES_PASSWORD }}
          database: ${{ secrets.POSTGRES_DB }}
          port: ${{ secrets.POSTGRES_PORT }}
        id: postgres
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      #- name: Update dependency graph
      #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      - name: Setup node v20
        uses: cd src/main/frontend | actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: cd src/main/frontend | npm i
      - run: cd src/main/frontend | npm run build
    # - run: npm run test
    #publish:
    # Need to get access to docker hub, which for now is not responding
    # - uses: mr-smithers-excellent/docker-build-push@v6
    #  with:
    #    image: docker-hub-repo/image-name
    #    registry: docker.io
    #    username: ${{ secrets.DOCKER_USERNAME }}
    #    password: ${{ secrets.DOCKER_PASSWORD }}
