name: Scanning for bugs with sonarqube

on:
  pull_request:
    branches: [ "master" ]

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.1
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectKey: "dndSonarChecks612"
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/main/frontend
    steps:
      - uses: actions/checkout@v4
      - uses: kitabisa/sonarqube-action@v1.2.1
        with:
          host: ${{ secrets.SONARQUBE_HOST }}
          login: ${{ secrets.SONARQUBE_TOKEN }}
          projectBaseDir: "src/main/frontend"
          projectKey: "dndSonarChecks612"